project:
  type: book
  output-dir: docs

book:
  title: Example Publication
  # subtitle: An example IUB Libraries Scholarly Communication publication
  description: An Example Publication of the IUB Libraries Scholarly Communication Deparment Non-Traditional Publishing Service
  # abstract: 
  doi: TK
  publisher: Scholarly Communication Department, Indiana University Bloomington Libraries
  publisher-place: Bloomington, IN
  author: 
    - name: 
        given: Adam
        family: Mazel
        literal: Adam Mazel
      attributes:
        corresponding: True
      affiliations:
        - name: Indiana University Bloomington Libraries
          department: Scholarly Communication
          address: 1320 E. Tenth Street
          city: Bloomington
          region: IN
          postal-code: 47405
          url: https://libraries.indiana.edu/
      orcid: 0000-0001-7241-0891 
      email: amazel@iu.edu
      url: https://libraries.indiana.edu/adam-mazel

  date: last-modified
  date-format: YYYY-MMMM-DD
  language: en-US
  downloads: [pdf, epub, docx]
  sharing: [twitter, facebook, linkedin]
  # call-number: 
  # genre: 
  type: document
  keyword: example, "library publishing", "scholarly communication", "indiana university bloomington", "indiana university libraries"
  license: "CC BY"
  cover-image: images/cover2.jpg
  cover-image-alt: book cover in IU colors with title, author, and IU logo
  site-url: https://iulibscholcomm.github.io/example-publication/
  repo-url: https://github.com/IULibScholComm/example-publication
  issue-url: https://github.com/IULibScholComm/example-publication/issues/new
  pdf-url: https://github.com/IULibScholComm/example-publication/blob/main/docs/Example-Publication.pdf
  repo-actions: [edit, issue, source]
  favicon: images/cover2.jpg
  # cookie-consent: false
  comments:
    hypothesis: 
      theme: classic
      showHighlights: whenSidebarOpen
  search: 
    location: sidebar
    type: overlay
    copy-button: true
  page-navigation: true
  back-to-top-navigation: true
  image: images/cover2.jpg
  reader-mode: true
  google-analytics: "G-PT4W2H086H"
  twitter-card: 
    description: An example IUB Libraries Scholarly Communication publication
    card-style: summary
    site: "@iulibraries"
  open-graph: true
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-chapter.qmd
    - references.qmd
  appendices: 
    - appendix.qmd
  sidebar:
    logo: images/cover2.jpg
    tools: 
      - icon: person
        href: https://amaze2.github.io/
      - icon: twitter
        href: https://twitter.com/iulibraries?lang=en

bibliography: references.bib

# references: 

# citation:
  # type: document
  # publisher: Scholarly Communication Department, Indiana University Bloomington Libraries
  # publisher-place: Bloomington, IN
  # doi: TK

# google-scholar: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-title: Contents
    toc-expand: true
    number-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    copyright: Adam Mazel
    date-modified: last-modified
    license: "CC BY"
  pdf:
    documentclass: book
    keep-tex: true
    toc: true
    toc-title: Contents
    lof: true
    lot: true
    number-sections: true
    fontsize: 11pt
    linkcolor: cyan
    papersize: letter
  epub:
    cover-image: images/cover2.jpg
    toc: true
    toc-title: Contents
    number-sections: true
  docx:
    toc: true
    toc-title: Contents
    number-sections: true
    lang: en-US
    date: last-modified
    author: Adam Mazel
